/**
 * Auto-generated story for <org-spinner>
 * Generated by scripts/generateStories.js — do not edit manually.
 * To customise, create spinner.stories.custom.ts alongside this file.
 */

import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import '../components/spinner.js';

type Story = StoryObj;

const meta: Meta = {
  title: 'Components/OrgSpinner',
  component: 'org-spinner',
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: 'Auto-generated story. Add a `spinner.mdx` file for full docs.',
      },
    },
  },
  argTypes: {
    size: {
      control: 'select',
      options: ["small","medium","large","xlarge"],
      description: 'Variant options',
    },
    color: { control: 'text' },
    label: { control: 'text' },
    variant: {
      control: 'select',
      options: ["text","circle","rect","card"],
      description: 'Variant options',
    },
    width: { control: 'text' },
    height: { control: 'text' },
    lines: { control: 'number' },
    animated: { control: 'boolean' },
  },
  render: (args) => {
    const el = document.createElement('org-spinner') as any;
  if (args.size !== undefined) el.size = args.size;
  if (args.color !== undefined) el.color = args.color;
  if (args.label !== undefined) el.label = args.label;
  if (args.variant !== undefined) el.variant = args.variant;
  if (args.width !== undefined) el.width = args.width;
  if (args.height !== undefined) el.height = args.height;
  if (args.lines !== undefined) el.lines = args.lines;
  if (args.animated !== undefined) el.animated = args.animated;

    el.textContent = el.textContent || 'OrgSpinner';
    return el;
  },
};

export default meta;

export const Playground: Story = {
  name: 'Playground',
  args: {
    size: "medium",
    color: '',
    label: 'Loading...',
    variant: "text",
    width: '',
    height: '',
    lines: 3,
    animated: true,
  },
};

export const Disabled: Story = {
  args: { ...Playground.args, disabled: true },
};

export const Text: Story = {
  args: { ...Playground.args, variant: 'text' },
  name: 'Text',
};

export const Circle: Story = {
  args: { ...Playground.args, variant: 'circle' },
  name: 'Circle',
};

export const Rect: Story = {
  args: { ...Playground.args, variant: 'rect' },
  name: 'Rect',
};

export const Card: Story = {
  args: { ...Playground.args, variant: 'card' },
  name: 'Card',
};
