#!/usr/bin/env node
/**
 * watch.js — Story Auto-Generator (Watch Mode)
 *
 * Watches src/components/ for file changes and auto-regenerates
 * the corresponding Storybook story on every save.
 *
 * Usage:
 *   node scripts/watch.js
 *   (or: npm run watch:stories)
 *
 * Behaviour:
 *   - Component added   → story created
 *   - Component changed → story regenerated
 *   - Component deleted → story deleted
 *
 * Uses only Node.js built-ins (fs.watch). Zero extra dependencies.
 */

const fs   = require('fs');
const path = require('path');

const ROOT          = path.join(__dirname, '..');
const COMPONENTS_DIR = path.join(ROOT, 'src', 'components');
const STORIES_DIR    = path.join(ROOT, 'src', 'stories');

// ─── Parsers (same as generateStories.js) ────────────────────────────────────

function extractProperties(src) {
  const props = [];
  const blockRegex =
    /@property\(\{[^}]*type:\s*(Boolean|String|Number|Array)[^}]*\}\)\s*\n?\s*(\w+)(?::\s*([^=\n;]+))?(?:\s*=\s*([^;\n]+))?/g;

  let match;
  while ((match = blockRegex.exec(src)) !== null) {
    const [, litType, name, typeAnnotation, rawDefault] = match;
    const annotation = typeAnnotation?.trim() ?? '';
    const defaultRaw = rawDefault?.trim() ?? '';
    const unionMatches = annotation.match(/'([^']+)'/g);

    if (unionMatches && unionMatches.length > 1) {
      const options    = unionMatches.map(v => v.replace(/'/g, ''));
      const defaultVal = defaultRaw.replace(/'/g, '') || options[0];
      props.push({ name, type: 'select', options, defaultValue: defaultVal });
    } else if (litType === 'Boolean') {
      props.push({ name, type: 'boolean', defaultValue: defaultRaw === 'true' });
    } else if (litType === 'Number') {
      props.push({ name, type: 'number', defaultValue: defaultRaw !== '' ? Number(defaultRaw) : 0 });
    } else if (litType === 'Array') {
      props.push({ name, type: 'object', defaultValue: [] });
    } else {
      props.push({ name, type: 'text', defaultValue: defaultRaw.replace(/['"]/g, '') || '' });
    }
  }
  return props;
}

function extractEvents(src) {
  const events = [];
  const re = /@fires\s+([\w:.-]+)/g;
  let m;
  while ((m = re.exec(src)) !== null) events.push(m[1]);
  return events;
}

function extractTagName(src) {
  const m = src.match(/@customElement\(['"]([^'"]+)['"]\)/);
  return m ? m[1] : null;
}

function extractClassName(src) {
  const m = src.match(/export class (\w+)/);
  return m ? m[1] : null;
}

// ─── Story generator ──────────────────────────────────────────────────────────

function generateArgTypes(props, events) {
  const lines = [];
  props.forEach(p => {
    if (p.type === 'select') {
      lines.push(`    ${p.name}: { control: 'select', options: ${JSON.stringify(p.options)} },`);
    } else {
      lines.push(`    ${p.name}: { control: '${p.type}' },`);
    }
  });
  events.forEach(event => {
    const handler = `on${event.replace(/[:-](.)/g, (_, c) => c.toUpperCase())}`;
    lines.push(`    '${handler}': { action: '${event}' },`);
  });
  return lines.join('\n');
}

function generateDefaultArgs(props) {
  return props.map(p => {
    const val = p.type === 'text'    ? `'${p.defaultValue}'`
              : p.type === 'select'  ? `'${p.defaultValue}'`
              : p.type === 'object'  ? '[]'
              : JSON.stringify(p.defaultValue);
    return `    ${p.name}: ${val},`;
  }).join('\n');
}

function generatePropAssignments(props) {
  return props.map(p =>
    `  if (args.${p.name} !== undefined) el.${p.name} = args.${p.name};`
  ).join('\n');
}

function generateEventListeners(events) {
  return events.map(event => {
    const handler = `on${event.replace(/[:-](.)/g, (_, c) => c.toUpperCase())}`;
    return `  el.addEventListener('${event}', args['${handler}'] ?? (() => {}));`;
  }).join('\n');
}

function buildStoryContent(componentName, tagName, className, props, events) {
  const variantProp = props.find(p => p.type === 'select' && p.name === 'variant');
  const variantStories = variantProp
    ? variantProp.options.map(opt => `
export const ${opt.charAt(0).toUpperCase() + opt.slice(1)}: Story = {
  name: '${opt}',
  args: { ...Playground.args, variant: '${opt}' },
};`).join('\n')
    : '';

  return `/**
 * Auto-generated by watch.js — do not edit manually.
 * Last updated: ${new Date().toISOString()}
 */

import type { Meta, StoryObj } from '@storybook/web-components';
import '../components/${componentName}.js';

type Story = StoryObj;

const meta: Meta = {
  title: 'Components/${className}',
  component: '${tagName}',
  parameters: { layout: 'centered' },
  argTypes: {
${generateArgTypes(props, events)}
  },
  render: (args) => {
    const el = document.createElement('${tagName}') as any;
${generatePropAssignments(props)}
${generateEventListeners(events)}
    el.textContent = el.textContent || '${className}';
    return el;
  },
};

export default meta;

export const Playground: Story = {
  args: {
${generateDefaultArgs(props)}
  },
};

export const DisabledState: Story = {
  name: 'Disabled',
  args: { ...Playground.args, disabled: true },
};
${variantStories}
`;
}

// ─── File operations ──────────────────────────────────────────────────────────

function regenerateStory(componentFile) {
  const componentName = componentFile.replace('.ts', '');
  const srcPath       = path.join(COMPONENTS_DIR, componentFile);
  const storyPath     = path.join(STORIES_DIR, `${componentName}.stories.ts`);

  try {
    const src       = fs.readFileSync(srcPath, 'utf8');
    const tagName   = extractTagName(src);
    const className = extractClassName(src);

    if (!tagName || !className) {
      log('warn', componentFile, 'missing @customElement or export class — skipping');
      return;
    }

    const props   = extractProperties(src);
    const events  = extractEvents(src);
    const content = buildStoryContent(componentName, tagName, className, props, events);

    fs.mkdirSync(STORIES_DIR, { recursive: true });
    fs.writeFileSync(storyPath, content, 'utf8');

    log('ok', componentFile, `→ ${componentName}.stories.ts (${props.length} props, ${events.length} events)`);
  } catch (err) {
    log('error', componentFile, err.message);
  }
}

function deleteStory(componentFile) {
  const componentName = componentFile.replace('.ts', '');
  const storyPath     = path.join(STORIES_DIR, `${componentName}.stories.ts`);
  if (fs.existsSync(storyPath)) {
    fs.unlinkSync(storyPath);
    log('delete', componentFile, `→ removed ${componentName}.stories.ts`);
  }
}

// ─── Logging ──────────────────────────────────────────────────────────────────

function timestamp() {
  return new Date().toTimeString().slice(0, 8);
}

function log(type, file, msg) {
  const icons = { ok: '✅', warn: '⚠️ ', error: '❌', delete: '🗑️ ', info: 'ℹ️ ', start: '👀' };
  console.log(`[${timestamp()}] ${icons[type] ?? '  '} ${file.padEnd(28)} ${msg}`);
}

// ─── Debounce ─────────────────────────────────────────────────────────────────

const debounceTimers = new Map();
function debounce(key, fn, delay = 120) {
  if (debounceTimers.has(key)) clearTimeout(debounceTimers.get(key));
  debounceTimers.set(key, setTimeout(() => { debounceTimers.delete(key); fn(); }, delay));
}

// ─── Watcher ──────────────────────────────────────────────────────────────────

function startWatcher() {
  if (!fs.existsSync(COMPONENTS_DIR)) {
    console.error(`❌  Components directory not found: ${COMPONENTS_DIR}`);
    process.exit(1);
  }

  // Initial pass — generate stories for all existing components
  const existing = fs.readdirSync(COMPONENTS_DIR).filter(f => f.endsWith('.ts'));
  console.log(`\n👀  Watching src/components/ for changes...\n`);
  console.log(`    Found ${existing.length} component(s) — generating initial stories:\n`);
  existing.forEach(f => regenerateStory(f));
  console.log(`\n    Watching for changes. Press Ctrl+C to stop.\n`);

  // Watch for changes
  fs.watch(COMPONENTS_DIR, { persistent: true }, (eventType, filename) => {
    if (!filename || !filename.endsWith('.ts')) return;

    debounce(filename, () => {
      const fullPath = path.join(COMPONENTS_DIR, filename);
      const exists   = fs.existsSync(fullPath);

      if (eventType === 'rename' && !exists) {
        deleteStory(filename);
      } else {
        regenerateStory(filename);
      }
    });
  });

  // Handle exit gracefully
  process.on('SIGINT', () => {
    console.log('\n\n👋  Watcher stopped.\n');
    process.exit(0);
  });
}

startWatcher();
